esphome:
  name: artnet-example

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable WiFi (required for ArtNet)
wifi:
  ssid: "your_wifi_ssid"
  password: "your_wifi_password"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ArtNet Receiver Fallback Hotspot"
    password: "12345678"

# Enable logging
logger:

# Enable Home Assistant API
api:

# Enable OTA updates
ota:
  platform: esphome

# Include our custom component from the local components directory
external_components:
  - source: components
  - source: ../esphome-dmx/components

dmx:
  - id: dmx_bus_a
    mode: send
    enable_pin:
      number: GPIO18
    tx_pin:
      number: GPIO16
    rx_pin:
      number: GPIO17
    dmx_port_id: 1

  - id: dmx_bus_b
    mode: receive
    enable_pin:
      number: GPIO23
    tx_pin:
      number: GPIO21
    rx_pin:
      number: GPIO22
    dmx_port_id: 2

artnet:
  output:
    address: 10.1.1.10
    flush_period: 10ms

  route:
    artnet_to_dmx:
      - dmx_id: dmx_bus_a
        universe: 1

    dmx_to_artnet:
      - dmx_id: dmx_bus_b
        universe: 2

sensor:
  - platform: artnet
    id: artnet_input_1
    name: "ArtNet Dimmer 1"
    universe: 1
    channel: 1

  - platform: artnet
    id: artnet_input_2
    name: "ArtNet Dimmer 2"
    universe: 1
    channel: 2

output:
  - platform: artnet
    id: artnet_output_1
    universe: 1
    channel: 1

  - platform: artnet
    id: artnet_output_2
    universe: 1
    channel: 2

  - platform: artnet
    id: artnet_output_3
    universe: 1
    channel: 3

light:
  - platform: rgb
    name: "Artnet input controlled RGB Light"
    red: artnet_output_1
    green: artnet_output_2
    blue: artnet_output_3
