esphome:
  name: artnet-dmx-converter

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable WiFi (required for ArtNet)
wifi:
  ssid: "YOUR_WIFI_SSID"
  password: "YOUR_WIFI_PASSWORD"
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ArtNet Test Fallback"
    password: "12345678"

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API (optional)
api:

# Enable OTA updates (optional)
ota:
  platform: esphome

# Include our custom component from the local components directory
external_components:
  - source: components

# Configure the ArtNet receiver with a few test channels
artnet_receiver:
  id: artnet_receiver_1
  artnet_universe: 0
  channels:
    - channel_number: 1
      name: "Test Channel 1"
      id: test_ch1
    - channel_number: 2
      name: "Test Channel 2"
      id: test_ch2
    - channel_number: 3
      name: "Test Channel 3"
      id: test_ch3